
server:
  port: 8080
spring:
  datasource:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        jdbc-url: jdbc:mysql://127.0.0.1:3306/shop_goods?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        jdbc-url: jdbc:mysql://127.0.0.1:3306/shop_order?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  application:
    name: springbootdemo
  rabbitmq:
    addresses: 192.168.99.100
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

# ====================MybatisPlus====================
mybatis-plus:
  #mapper-config: mapper/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.taotao.*.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#sping:
 # devtools:
 #   restart:
 #     enabled: true  #开启热部署
 #     additional-paths: src/main/java/  #设置重启的目录
